// <auto-generated />
using System;
using FriendsNess.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FriendsNess.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220501135216_UpdateExercicies")]
    partial class UpdateExercicies
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes", (string)null);
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.Key", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("DataProtected")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsX509Certificate")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Use")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Use");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Key");

                    b.HasIndex("ConsumedTime");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants", (string)null);
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Exercices.Exercice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("ExercicedBodyParts")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Exercices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            ExercicedBodyParts = 2,
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            ExercicedBodyParts = 5,
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            ExercicedBodyParts = 8,
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            ExercicedBodyParts = 6,
                            Name = "Shoulder Press"
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            ExercicedBodyParts = 0,
                            Name = "Pull Ups"
                        },
                        new
                        {
                            Id = 6,
                            Category = 3,
                            ExercicedBodyParts = 2,
                            Name = "Dumbbell Bench Press"
                        },
                        new
                        {
                            Id = 7,
                            Category = 3,
                            ExercicedBodyParts = 1,
                            Name = "Dumbbell Curl"
                        },
                        new
                        {
                            Id = 8,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Bent Over Row"
                        },
                        new
                        {
                            Id = 9,
                            Category = 1,
                            ExercicedBodyParts = 2,
                            Name = "Push Ups"
                        },
                        new
                        {
                            Id = 10,
                            Category = 0,
                            ExercicedBodyParts = 5,
                            Name = "Front Squat"
                        },
                        new
                        {
                            Id = 11,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = 12,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Sled Leg Press"
                        },
                        new
                        {
                            Id = 13,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Incline Bench Press"
                        },
                        new
                        {
                            Id = 14,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dips"
                        },
                        new
                        {
                            Id = 15,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Power Clean"
                        },
                        new
                        {
                            Id = 16,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = 17,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Incline Dumbbell Bench Press"
                        },
                        new
                        {
                            Id = 18,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hex Bar Deadlift"
                        },
                        new
                        {
                            Id = 19,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Military Press"
                        },
                        new
                        {
                            Id = 20,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Chin Ups"
                        },
                        new
                        {
                            Id = 21,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Sumo Deadlift"
                        },
                        new
                        {
                            Id = 22,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Row"
                        },
                        new
                        {
                            Id = 23,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Horizontal Leg Press"
                        },
                        new
                        {
                            Id = 24,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hip Thrust"
                        },
                        new
                        {
                            Id = 25,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Lateral Raise"
                        },
                        new
                        {
                            Id = 26,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Romanian Deadlift"
                        },
                        new
                        {
                            Id = 27,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Leg Extension"
                        },
                        new
                        {
                            Id = 28,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Chest Press"
                        },
                        new
                        {
                            Id = 29,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Clean and Jerk"
                        },
                        new
                        {
                            Id = 30,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Tricep Pushdown"
                        },
                        new
                        {
                            Id = 31,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Snatch"
                        },
                        new
                        {
                            Id = 32,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Clean"
                        },
                        new
                        {
                            Id = 33,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Seated Cable Row"
                        },
                        new
                        {
                            Id = 34,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hammer Curl"
                        },
                        new
                        {
                            Id = 35,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Push Press"
                        },
                        new
                        {
                            Id = 36,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Barbell Shrug"
                        },
                        new
                        {
                            Id = 37,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Decline Bench Press"
                        },
                        new
                        {
                            Id = 38,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Close Grip Bench Press"
                        },
                        new
                        {
                            Id = 39,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Clean and Press"
                        },
                        new
                        {
                            Id = 40,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Seated Leg Curl"
                        },
                        new
                        {
                            Id = 41,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Fly"
                        },
                        new
                        {
                            Id = 42,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "T Bar Row"
                        },
                        new
                        {
                            Id = 43,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Machine Calf Raise"
                        },
                        new
                        {
                            Id = 44,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Lying Leg Curl"
                        },
                        new
                        {
                            Id = 45,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Lunge"
                        },
                        new
                        {
                            Id = 46,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "EZ Bar Curl"
                        },
                        new
                        {
                            Id = 47,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Tricep Rope Pushdown"
                        },
                        new
                        {
                            Id = 48,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Shrug"
                        },
                        new
                        {
                            Id = 49,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Lying Tricep Extension"
                        },
                        new
                        {
                            Id = 50,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Seated Shoulder Press"
                        },
                        new
                        {
                            Id = 51,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Goblet Squat"
                        },
                        new
                        {
                            Id = 52,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Tricep Extension"
                        },
                        new
                        {
                            Id = 53,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Rack Pull"
                        },
                        new
                        {
                            Id = 54,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Preacher Curl"
                        },
                        new
                        {
                            Id = 55,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Vertical Leg Press"
                        },
                        new
                        {
                            Id = 56,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Pendlay Row"
                        },
                        new
                        {
                            Id = 57,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Bulgarian Split Squat"
                        },
                        new
                        {
                            Id = 58,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Machine Shoulder Press"
                        },
                        new
                        {
                            Id = 59,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Machine Chest Fly"
                        },
                        new
                        {
                            Id = 60,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Upright Row"
                        },
                        new
                        {
                            Id = 61,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Tricep Extension"
                        },
                        new
                        {
                            Id = 62,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Box Squat"
                        },
                        new
                        {
                            Id = 63,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Front Raise"
                        },
                        new
                        {
                            Id = 64,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hack Squat"
                        },
                        new
                        {
                            Id = 65,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Concentration Curl"
                        },
                        new
                        {
                            Id = 66,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable Bicep Curl"
                        },
                        new
                        {
                            Id = 67,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Sit Ups"
                        },
                        new
                        {
                            Id = 68,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable Lateral Raise"
                        },
                        new
                        {
                            Id = 69,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Arnold Press"
                        },
                        new
                        {
                            Id = 70,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Bodyweight Squat"
                        },
                        new
                        {
                            Id = 71,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Bulgarian Split Squat"
                        },
                        new
                        {
                            Id = 72,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Floor Press"
                        },
                        new
                        {
                            Id = 73,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Incline Dumbbell Fly"
                        },
                        new
                        {
                            Id = 74,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Good Morning"
                        },
                        new
                        {
                            Id = 75,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable Fly"
                        },
                        new
                        {
                            Id = 76,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hang Clean"
                        },
                        new
                        {
                            Id = 77,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Seated Calf Raise"
                        },
                        new
                        {
                            Id = 78,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Muscle Ups"
                        },
                        new
                        {
                            Id = 79,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Stiff Leg Deadlift"
                        },
                        new
                        {
                            Id = 80,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Barbell Lunge"
                        },
                        new
                        {
                            Id = 81,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Zercher Squat"
                        },
                        new
                        {
                            Id = 82,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Romanian Deadlift"
                        },
                        new
                        {
                            Id = 83,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Overhead Squat"
                        },
                        new
                        {
                            Id = 84,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Pullover"
                        },
                        new
                        {
                            Id = 85,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable Crunch"
                        },
                        new
                        {
                            Id = 86,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Lying Dumbbell Tricep Extension"
                        },
                        new
                        {
                            Id = 87,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Smite Machine Bench Press"
                        },
                        new
                        {
                            Id = 88,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Face Pull"
                        },
                        new
                        {
                            Id = 89,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hip Abduction"
                        },
                        new
                        {
                            Id = 90,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Incline Dumbbell Curl"
                        },
                        new
                        {
                            Id = 91,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Floor Press"
                        },
                        new
                        {
                            Id = 92,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Thruster"
                        },
                        new
                        {
                            Id = 93,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Reverse Fly"
                        },
                        new
                        {
                            Id = 94,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Machine Row"
                        },
                        new
                        {
                            Id = 95,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Push Jerk"
                        },
                        new
                        {
                            Id = 96,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Wrist Curl"
                        },
                        new
                        {
                            Id = 97,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Smith Machine Squat"
                        },
                        new
                        {
                            Id = 98,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Power Snatch"
                        },
                        new
                        {
                            Id = 99,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hip Adduction"
                        },
                        new
                        {
                            Id = 100,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Tricep Kickback"
                        },
                        new
                        {
                            Id = 101,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Chest Supported Dumbbell Row"
                        },
                        new
                        {
                            Id = 102,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Decline Dumbbell Bench Press"
                        },
                        new
                        {
                            Id = 103,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Split Squat"
                        },
                        new
                        {
                            Id = 104,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Seated Dip Machine"
                        },
                        new
                        {
                            Id = 105,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Machine Seated Crunch"
                        },
                        new
                        {
                            Id = 106,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable Pull Through"
                        },
                        new
                        {
                            Id = 107,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Reverse Grip Bench Press"
                        },
                        new
                        {
                            Id = 108,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Crunches"
                        },
                        new
                        {
                            Id = 109,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Reverse Wrist Curl"
                        },
                        new
                        {
                            Id = 110,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Landmine Squat"
                        },
                        new
                        {
                            Id = 111,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Standing Leg Curl"
                        },
                        new
                        {
                            Id = 112,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Barbell Calf Raise"
                        },
                        new
                        {
                            Id = 113,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Reverse Barbell Curl"
                        },
                        new
                        {
                            Id = 114,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "One Arm Cable Bicep Curl"
                        },
                        new
                        {
                            Id = 115,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Squat"
                        },
                        new
                        {
                            Id = 116,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Barbell Glute Bridge"
                        },
                        new
                        {
                            Id = 117,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Barbell Reverse Lunge"
                        },
                        new
                        {
                            Id = 118,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Deficit Deadlift"
                        },
                        new
                        {
                            Id = 119,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Calf Raise"
                        },
                        new
                        {
                            Id = 120,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable Crossover"
                        },
                        new
                        {
                            Id = 121,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Machine Tricep Extension"
                        },
                        new
                        {
                            Id = 122,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Paused Bench Press"
                        },
                        new
                        {
                            Id = 123,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "One Arm Push Ups"
                        },
                        new
                        {
                            Id = 124,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Close Grip Lat Pulldown"
                        },
                        new
                        {
                            Id = 125,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Neck Curl"
                        },
                        new
                        {
                            Id = 126,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Deadlift"
                        },
                        new
                        {
                            Id = 127,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Strict Curl"
                        },
                        new
                        {
                            Id = 128,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable Reverse Fly"
                        },
                        new
                        {
                            Id = 129,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable Overhead Tricep Extension"
                        },
                        new
                        {
                            Id = 130,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Belt Squat"
                        },
                        new
                        {
                            Id = 131,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Upright Row"
                        },
                        new
                        {
                            Id = 132,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Barbell Hack Squat"
                        },
                        new
                        {
                            Id = 133,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Safety Bar Squat"
                        },
                        new
                        {
                            Id = 134,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Machine Bicep Curl"
                        },
                        new
                        {
                            Id = 135,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Machine Reverse Fly"
                        },
                        new
                        {
                            Id = 136,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Behind The Neck Press"
                        },
                        new
                        {
                            Id = 137,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Bench Pin Press"
                        },
                        new
                        {
                            Id = 138,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Wrist Curl"
                        },
                        new
                        {
                            Id = 139,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Barbell Front Raise"
                        },
                        new
                        {
                            Id = 140,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Clean High Pull"
                        },
                        new
                        {
                            Id = 141,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Single Leg Press"
                        },
                        new
                        {
                            Id = 142,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Close Grip Dumbbell Bench Press"
                        },
                        new
                        {
                            Id = 143,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Long Press"
                        },
                        new
                        {
                            Id = 144,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Reverse Grip Lat Pulldown"
                        },
                        new
                        {
                            Id = 145,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Bench Pull"
                        },
                        new
                        {
                            Id = 146,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Pause Squat"
                        },
                        new
                        {
                            Id = 147,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Handstand Push Ups"
                        },
                        new
                        {
                            Id = 148,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Diamond Push Ups"
                        },
                        new
                        {
                            Id = 149,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Single Leg Romanian Deadlift"
                        },
                        new
                        {
                            Id = 150,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Sled Press Calf Raise"
                        },
                        new
                        {
                            Id = 151,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable Woodchoppers"
                        },
                        new
                        {
                            Id = 152,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Clean Pull"
                        },
                        new
                        {
                            Id = 153,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Split Jerk"
                        },
                        new
                        {
                            Id = 154,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Straight Arm Pulldown"
                        },
                        new
                        {
                            Id = 155,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Sumo Squat"
                        },
                        new
                        {
                            Id = 156,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Incline Hammer Curl"
                        },
                        new
                        {
                            Id = 157,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Snatch Deadlift"
                        },
                        new
                        {
                            Id = 158,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Preacher Curl"
                        },
                        new
                        {
                            Id = 159,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Side Bend"
                        },
                        new
                        {
                            Id = 160,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Machine Back Extension"
                        },
                        new
                        {
                            Id = 161,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Burpees"
                        },
                        new
                        {
                            Id = 162,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hang Power Clean"
                        },
                        new
                        {
                            Id = 163,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Yates Row"
                        },
                        new
                        {
                            Id = 164,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Jefferson Deadlift"
                        },
                        new
                        {
                            Id = 165,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Barbell Pullover"
                        },
                        new
                        {
                            Id = 166,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Snatch"
                        },
                        new
                        {
                            Id = 167,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Single Leg Deadlift"
                        },
                        new
                        {
                            Id = 168,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Pause Deadlift"
                        },
                        new
                        {
                            Id = 169,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Machine Lateral Raise"
                        },
                        new
                        {
                            Id = 170,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Landmine Press"
                        },
                        new
                        {
                            Id = 171,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Muscle Snatch"
                        },
                        new
                        {
                            Id = 172,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Wide Grip Bench Press"
                        },
                        new
                        {
                            Id = 173,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Seated Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = 174,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Reverse Grip Tricep Pushdown"
                        },
                        new
                        {
                            Id = 175,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Bench Pull"
                        },
                        new
                        {
                            Id = 176,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable Kickback"
                        },
                        new
                        {
                            Id = 177,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Neck Extension"
                        },
                        new
                        {
                            Id = 178,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Z Press"
                        },
                        new
                        {
                            Id = 179,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Reverse Curl"
                        },
                        new
                        {
                            Id = 180,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Renegade Row"
                        },
                        new
                        {
                            Id = 181,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Shoulder Pin Press"
                        },
                        new
                        {
                            Id = 182,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Zottman Curl"
                        },
                        new
                        {
                            Id = 183,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Viking Press"
                        },
                        new
                        {
                            Id = 184,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Neutral Grip Pull Ups"
                        },
                        new
                        {
                            Id = 185,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Tate Press"
                        },
                        new
                        {
                            Id = 186,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Lunge"
                        },
                        new
                        {
                            Id = 187,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Snatch Pull"
                        },
                        new
                        {
                            Id = 188,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Spider Curl"
                        },
                        new
                        {
                            Id = 189,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Z Press"
                        },
                        new
                        {
                            Id = 190,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "JM Press"
                        },
                        new
                        {
                            Id = 191,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Pin Squat"
                        },
                        new
                        {
                            Id = 192,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "One Arm Pull Ups"
                        },
                        new
                        {
                            Id = 193,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Wall Ball"
                        },
                        new
                        {
                            Id = 194,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Glute Bridge"
                        },
                        new
                        {
                            Id = 195,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Back Extension"
                        },
                        new
                        {
                            Id = 196,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Pistol Squat"
                        },
                        new
                        {
                            Id = 197,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hanging Leg Raise"
                        },
                        new
                        {
                            Id = 198,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Inverted Row"
                        },
                        new
                        {
                            Id = 199,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Russian Twist"
                        },
                        new
                        {
                            Id = 200,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Bent Over Dumbbell Row"
                        },
                        new
                        {
                            Id = 201,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Bodyweight Calf Raise"
                        },
                        new
                        {
                            Id = 202,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Lying Leg Raise"
                        },
                        new
                        {
                            Id = 203,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Seated Dumbbell Tricep Extension"
                        },
                        new
                        {
                            Id = 204,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Bench Dips"
                        },
                        new
                        {
                            Id = 205,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Ring Dips"
                        },
                        new
                        {
                            Id = 206,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Toes To Bar"
                        },
                        new
                        {
                            Id = 207,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cheat Curl"
                        },
                        new
                        {
                            Id = 208,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Seated Dumbbell Curl"
                        },
                        new
                        {
                            Id = 209,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Front Squat"
                        },
                        new
                        {
                            Id = 210,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Walking Lung"
                        },
                        new
                        {
                            Id = 211,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Decline Push Ups"
                        },
                        new
                        {
                            Id = 212,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Ab Wheel Rollout"
                        },
                        new
                        {
                            Id = 213,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Reverse Lunge"
                        },
                        new
                        {
                            Id = 214,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Reverse Wrist Curl"
                        },
                        new
                        {
                            Id = 215,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hanging Knee Raise"
                        },
                        new
                        {
                            Id = 216,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Glute Ham Raise"
                        },
                        new
                        {
                            Id = 217,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Nordic Hamstring Curl"
                        },
                        new
                        {
                            Id = 218,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Decline Crunch"
                        },
                        new
                        {
                            Id = 219,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Close Grip Push Up"
                        },
                        new
                        {
                            Id = 220,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Decline Sit Up"
                        },
                        new
                        {
                            Id = 221,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Jumping Jack"
                        },
                        new
                        {
                            Id = 222,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Squat Jumps"
                        },
                        new
                        {
                            Id = 223,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Push Press"
                        },
                        new
                        {
                            Id = 224,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Incline Push Up"
                        },
                        new
                        {
                            Id = 225,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell External Rotation"
                        },
                        new
                        {
                            Id = 226,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "One Arm Seated Cable Row"
                        },
                        new
                        {
                            Id = 227,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable Upright Row"
                        },
                        new
                        {
                            Id = 228,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Pike Push Up"
                        },
                        new
                        {
                            Id = 229,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Smith Machine Shrug"
                        },
                        new
                        {
                            Id = 230,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Bicycle Crunch"
                        },
                        new
                        {
                            Id = 231,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Ring Muscle Ups"
                        },
                        new
                        {
                            Id = 232,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Reverse Crunches"
                        },
                        new
                        {
                            Id = 233,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Split Squat"
                        },
                        new
                        {
                            Id = 234,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Incline And Raise"
                        },
                        new
                        {
                            Id = 235,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Side Lunge"
                        },
                        new
                        {
                            Id = 236,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Sissy Squat"
                        },
                        new
                        {
                            Id = 237,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "One Arm Lat Pulldown"
                        },
                        new
                        {
                            Id = 238,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Barbell Power Shrug"
                        },
                        new
                        {
                            Id = 239,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Flutter Kicks"
                        },
                        new
                        {
                            Id = 240,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Single Arm Landmine Press"
                        },
                        new
                        {
                            Id = 241,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Single Leg Seated Calf Raise"
                        },
                        new
                        {
                            Id = 242,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Donkey Calf Raise"
                        },
                        new
                        {
                            Id = 243,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Machine Shrug"
                        },
                        new
                        {
                            Id = 244,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable Leg Extension"
                        },
                        new
                        {
                            Id = 245,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Decline Dumbbell Fly"
                        },
                        new
                        {
                            Id = 246,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "One Arm Pulldown"
                        },
                        new
                        {
                            Id = 247,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Mountain Climbers"
                        },
                        new
                        {
                            Id = 248,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Reverse Curl"
                        },
                        new
                        {
                            Id = 249,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell High Pull"
                        },
                        new
                        {
                            Id = 250,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hex Bar Shrug"
                        },
                        new
                        {
                            Id = 251,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable Hammer Curl"
                        },
                        new
                        {
                            Id = 252,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Clap Pull Up"
                        },
                        new
                        {
                            Id = 253,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Single Leg Dumbbell Deadlift"
                        },
                        new
                        {
                            Id = 254,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Face Pull"
                        },
                        new
                        {
                            Id = 255,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Side Leg Lift"
                        },
                        new
                        {
                            Id = 256,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable External Rotation"
                        },
                        new
                        {
                            Id = 257,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Hang Clean"
                        },
                        new
                        {
                            Id = 258,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Zercher Deadlift"
                        },
                        new
                        {
                            Id = 259,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable Shrug"
                        },
                        new
                        {
                            Id = 260,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Paused Squat"
                        },
                        new
                        {
                            Id = 261,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Half Squat"
                        },
                        new
                        {
                            Id = 262,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Side Crunch"
                        },
                        new
                        {
                            Id = 263,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Jefferson Squat"
                        },
                        new
                        {
                            Id = 264,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Bent Arm Barbell Pullover"
                        },
                        new
                        {
                            Id = 265,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Clean and Press"
                        },
                        new
                        {
                            Id = 266,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Close Grip Incline Bench Press"
                        },
                        new
                        {
                            Id = 267,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Overhead Cable Curl"
                        },
                        new
                        {
                            Id = 268,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Floor Hip Abduction"
                        },
                        new
                        {
                            Id = 269,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hang Snatch"
                        },
                        new
                        {
                            Id = 270,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Standing Cable Crunch"
                        },
                        new
                        {
                            Id = 271,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Behind The Back Barbell Shrug"
                        },
                        new
                        {
                            Id = 272,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Archer Push Ups"
                        },
                        new
                        {
                            Id = 273,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Squat Thrust"
                        },
                        new
                        {
                            Id = 274,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hip Extension"
                        },
                        new
                        {
                            Id = 275,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Roman Chair Side Bend"
                        },
                        new
                        {
                            Id = 276,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Glute Kickback"
                        },
                        new
                        {
                            Id = 277,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Superman"
                        },
                        new
                        {
                            Id = 278,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Meadows Row"
                        },
                        new
                        {
                            Id = 279,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Spoto Press"
                        },
                        new
                        {
                            Id = 280,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Thruster"
                        },
                        new
                        {
                            Id = 281,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Scissor Kicks"
                        },
                        new
                        {
                            Id = 282,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Walking Calf Raise"
                        },
                        new
                        {
                            Id = 283,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Reverse Hyperextension"
                        },
                        new
                        {
                            Id = 284,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Behind The Back Deadlift"
                        },
                        new
                        {
                            Id = 285,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Floor Hip Extension"
                        },
                        new
                        {
                            Id = 286,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Incline Cable Curl"
                        },
                        new
                        {
                            Id = 287,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "High Pulley Crunch"
                        },
                        new
                        {
                            Id = 288,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Lying Cable Curl"
                        });
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Exercices.ExerciceSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Repetitions")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<int>("UserExerciceExerciceId")
                        .HasColumnType("int");

                    b.Property<int>("UserExerciceId")
                        .HasColumnType("int");

                    b.Property<int>("UserExerciceUserId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("UserExerciceUserId", "UserExerciceExerciceId");

                    b.ToTable("ExerciceSet");
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Exercices.UserExercice", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciceId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ExerciceId");

                    b.HasIndex("ExerciceId");

                    b.ToTable("UserExercices");
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Users.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Users.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Exercices.ExerciceSet", b =>
                {
                    b.HasOne("FriendsNess.Shared.Domain.Exercices.UserExercice", "UserExercice")
                        .WithMany("ExerciceSets")
                        .HasForeignKey("UserExerciceUserId", "UserExerciceExerciceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserExercice");
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Exercices.UserExercice", b =>
                {
                    b.HasOne("FriendsNess.Shared.Domain.Exercices.Exercice", "Exercice")
                        .WithMany("ExerciceUsers")
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FriendsNess.Shared.Domain.Users.ApplicationUser", "User")
                        .WithMany("UserExercices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("FriendsNess.Shared.Domain.Users.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("FriendsNess.Shared.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("FriendsNess.Shared.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("FriendsNess.Shared.Domain.Users.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FriendsNess.Shared.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("FriendsNess.Shared.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Exercices.Exercice", b =>
                {
                    b.Navigation("ExerciceUsers");
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Exercices.UserExercice", b =>
                {
                    b.Navigation("ExerciceSets");
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Users.ApplicationUser", b =>
                {
                    b.Navigation("UserExercices");
                });
#pragma warning restore 612, 618
        }
    }
}
