// <auto-generated />
using System;
using FriendsNess.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FriendsNess.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220430100454_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes", (string)null);
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.Key", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("DataProtected")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsX509Certificate")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Use")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Use");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Key");

                    b.HasIndex("ConsumedTime");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants", (string)null);
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Exercices.Exercice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("ExercicedBodyParts")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Exercices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            ExercicedBodyParts = 2,
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Squat"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Shoulder Press"
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Pull Ups"
                        },
                        new
                        {
                            Id = 6,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Bench Press"
                        },
                        new
                        {
                            Id = 7,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Bumbbell Curl"
                        },
                        new
                        {
                            Id = 8,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Bent Over Row"
                        },
                        new
                        {
                            Id = 9,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Push Ups"
                        },
                        new
                        {
                            Id = 10,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Front Squat"
                        },
                        new
                        {
                            Id = 11,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = 12,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Sled Leg Press"
                        },
                        new
                        {
                            Id = 13,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Incline Bench Press"
                        },
                        new
                        {
                            Id = 14,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dips"
                        },
                        new
                        {
                            Id = 15,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Power Clean"
                        },
                        new
                        {
                            Id = 16,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Lat Pulldown"
                        },
                        new
                        {
                            Id = 17,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Incline Dumbbell Bench Press"
                        },
                        new
                        {
                            Id = 18,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hex Bar Deadlift"
                        },
                        new
                        {
                            Id = 19,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Military Press"
                        },
                        new
                        {
                            Id = 20,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Chin Ups"
                        },
                        new
                        {
                            Id = 21,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Sumo Deadlift"
                        },
                        new
                        {
                            Id = 22,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Row"
                        },
                        new
                        {
                            Id = 23,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Horizontal Leg Press"
                        },
                        new
                        {
                            Id = 24,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hip Thrust"
                        },
                        new
                        {
                            Id = 25,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Lateral Raise"
                        },
                        new
                        {
                            Id = 26,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Romanian Deadlift"
                        },
                        new
                        {
                            Id = 27,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Leg Extension"
                        },
                        new
                        {
                            Id = 28,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Chest Press"
                        },
                        new
                        {
                            Id = 29,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Clean and Jerk"
                        },
                        new
                        {
                            Id = 30,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Tricep Pushdown"
                        },
                        new
                        {
                            Id = 31,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Snatch"
                        },
                        new
                        {
                            Id = 32,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Clean"
                        },
                        new
                        {
                            Id = 33,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Seated Cable Row"
                        },
                        new
                        {
                            Id = 34,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hammer Curl"
                        },
                        new
                        {
                            Id = 35,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Push Press"
                        },
                        new
                        {
                            Id = 36,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Barbell Shrug"
                        },
                        new
                        {
                            Id = 37,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Decline Bench Press"
                        },
                        new
                        {
                            Id = 38,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Close Grip Bench Press"
                        },
                        new
                        {
                            Id = 39,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Clean and Press"
                        },
                        new
                        {
                            Id = 40,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Seated Leg Curl"
                        },
                        new
                        {
                            Id = 41,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Fly"
                        },
                        new
                        {
                            Id = 42,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "T Bar Row"
                        },
                        new
                        {
                            Id = 43,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Machine Calf Raise"
                        },
                        new
                        {
                            Id = 44,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Lying Leg Curl"
                        },
                        new
                        {
                            Id = 45,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Lunge"
                        },
                        new
                        {
                            Id = 46,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "EZ Bar Curl"
                        },
                        new
                        {
                            Id = 47,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Tricep Rope Pushdown"
                        },
                        new
                        {
                            Id = 48,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Shrug"
                        },
                        new
                        {
                            Id = 49,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Lying Tricep Extension"
                        },
                        new
                        {
                            Id = 50,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Seated Shoulder Press"
                        },
                        new
                        {
                            Id = 51,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Goblet Squat"
                        },
                        new
                        {
                            Id = 52,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Tricep Extension"
                        },
                        new
                        {
                            Id = 53,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Rack Pull"
                        },
                        new
                        {
                            Id = 54,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Preacher Curl"
                        },
                        new
                        {
                            Id = 55,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Vertical Leg Press"
                        },
                        new
                        {
                            Id = 56,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Pendlay Row"
                        },
                        new
                        {
                            Id = 57,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Bulgarian Split Squat"
                        },
                        new
                        {
                            Id = 58,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Machine Shoulder Press"
                        },
                        new
                        {
                            Id = 59,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Machine Chest Fly"
                        },
                        new
                        {
                            Id = 60,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Upright Row"
                        },
                        new
                        {
                            Id = 61,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Tricep Extension"
                        },
                        new
                        {
                            Id = 62,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Box Squat"
                        },
                        new
                        {
                            Id = 63,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Front Raise"
                        },
                        new
                        {
                            Id = 64,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hack Squat"
                        },
                        new
                        {
                            Id = 65,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Concentration Curl"
                        },
                        new
                        {
                            Id = 66,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable Bicep Curl"
                        },
                        new
                        {
                            Id = 67,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Sit Ups"
                        },
                        new
                        {
                            Id = 68,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable Lateral Raise"
                        },
                        new
                        {
                            Id = 69,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Arnold Press"
                        },
                        new
                        {
                            Id = 70,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Bodyweight Squat"
                        },
                        new
                        {
                            Id = 71,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Bulgarian Split Squat"
                        },
                        new
                        {
                            Id = 72,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Floor Press"
                        },
                        new
                        {
                            Id = 73,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Incline Dumbbell Fly"
                        },
                        new
                        {
                            Id = 74,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Good Morning"
                        },
                        new
                        {
                            Id = 75,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable Fly"
                        },
                        new
                        {
                            Id = 76,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hang Clean"
                        },
                        new
                        {
                            Id = 77,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Seated Calf Raise"
                        },
                        new
                        {
                            Id = 78,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Muscle Ups"
                        },
                        new
                        {
                            Id = 79,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Stiff Leg Deadlift"
                        },
                        new
                        {
                            Id = 80,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Barbell Lunge"
                        },
                        new
                        {
                            Id = 81,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Zercher Squat"
                        },
                        new
                        {
                            Id = 82,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Romanian Deadlift"
                        },
                        new
                        {
                            Id = 83,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Overhead Squat"
                        },
                        new
                        {
                            Id = 84,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Pullover"
                        },
                        new
                        {
                            Id = 85,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Cable Crunch"
                        },
                        new
                        {
                            Id = 86,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Lying Dumbbell Tricep Extension"
                        },
                        new
                        {
                            Id = 87,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Smite Machine Bench Press"
                        },
                        new
                        {
                            Id = 88,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Face Pull"
                        },
                        new
                        {
                            Id = 89,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hip Abduction"
                        },
                        new
                        {
                            Id = 90,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Incline Dumbbell Curl"
                        },
                        new
                        {
                            Id = 91,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Floor Press"
                        },
                        new
                        {
                            Id = 92,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Thruster"
                        },
                        new
                        {
                            Id = 93,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Dumbbell Reverse Fly"
                        },
                        new
                        {
                            Id = 94,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Machine Row"
                        },
                        new
                        {
                            Id = 95,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Push Jerk"
                        },
                        new
                        {
                            Id = 96,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Wrist Curl"
                        },
                        new
                        {
                            Id = 97,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Smith Machine Squat"
                        },
                        new
                        {
                            Id = 98,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Power Snatch"
                        },
                        new
                        {
                            Id = 99,
                            Category = 0,
                            ExercicedBodyParts = 0,
                            Name = "Hip Adduction"
                        });
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Exercices.ExerciceSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Repetitions")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<int>("UserExerciceExerciceId")
                        .HasColumnType("int");

                    b.Property<int>("UserExerciceId")
                        .HasColumnType("int");

                    b.Property<int>("UserExerciceUserId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("UserExerciceUserId", "UserExerciceExerciceId");

                    b.ToTable("ExerciceSet");
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Exercices.UserExercice", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ExerciceId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ExerciceId");

                    b.HasIndex("ExerciceId");

                    b.ToTable("UserExercices");
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Users.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Users.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Exercices.ExerciceSet", b =>
                {
                    b.HasOne("FriendsNess.Shared.Domain.Exercices.UserExercice", "UserExercice")
                        .WithMany("ExerciceSets")
                        .HasForeignKey("UserExerciceUserId", "UserExerciceExerciceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserExercice");
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Exercices.UserExercice", b =>
                {
                    b.HasOne("FriendsNess.Shared.Domain.Exercices.Exercice", "Exercice")
                        .WithMany("ExerciceUsers")
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FriendsNess.Shared.Domain.Users.ApplicationUser", "User")
                        .WithMany("UserExercices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("FriendsNess.Shared.Domain.Users.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("FriendsNess.Shared.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("FriendsNess.Shared.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("FriendsNess.Shared.Domain.Users.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FriendsNess.Shared.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("FriendsNess.Shared.Domain.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Exercices.Exercice", b =>
                {
                    b.Navigation("ExerciceUsers");
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Exercices.UserExercice", b =>
                {
                    b.Navigation("ExerciceSets");
                });

            modelBuilder.Entity("FriendsNess.Shared.Domain.Users.ApplicationUser", b =>
                {
                    b.Navigation("UserExercices");
                });
#pragma warning restore 612, 618
        }
    }
}
